### ISSUE TITLE
Quiz Question #10

### ISSUE THREAD

**Issue by emilia-m26** [learn-co-curriculum/git-version-control-quiz#1]
Hello, not sure if this would qualify as a review of content.

Quiz question #10 asks... "Which of the following is the correct way to send code to a remote repo for the first time?"

The options are git push, git push origin master, git send, git push new. 

According to the lesson read before the quiz, "the first time you push code up to a newly-added remote repository, use the -u flag to tell Git to "save" the remote repository as the default push destination: git push -u origin master. For every subsequent push, you only need to enter git push".

I selected the git push origin master as the response and the quiz marks as correct. It also is the response that makes the most sense from all the options. But the lesson is a bit misleading is stating to use -u flag the first time, I'd assume the options on the quiz would have a -u flag since the question specifically asked for sending coding to the repo for the first time.

Thanks so much for your time in advance!

**Comment by sgharms** [comment]
Thanks for pointing this out, we'll review it.

**Comment by sgharms** [comment]
We made the edit. You're right! Thanks
